In [24]:
import numpy as n
world_size = 4
reward = -1.0
action_prob = 0.25
nextstate = []

In [25]:
world = n.zeros((world_size,world_size))
policy = n.zeros((world_size,world_size))


In [26]:
actions = ['l','r','u','d']

In [27]:
for i in range(0,world_size):
    nextstate.append([])
    for j in range(world_size):
        nexts = dict()
        if i==0:
            nexts['u'] = [i,j]
        else:
            nexts['u'] = [i-1,j]
        if i==world_size-1:
            nexts['d'] = [i,j]
        else:
            nexts['d'] = [i+1,j]
        if j==0:
            nexts['l'] = [i,j]
        else:
            nexts['l'] = [i,j-1]
        if j==world_size-1:
            nexts['r'] = [i,j]
        else:
            nexts['r'] = [i,j+1]    
        nextstate[i].append(nexts)    

In [28]:
states = []
for i in range(world_size):
    for j in range(world_size):
        if(i==0 and j==0) or (i== world_size-1 and j== world_size-1):
            continue
        else:
            states.append([i,j])
        

In [29]:
while True:
    
    newworld = n.zeros((world_size,world_size))
    
    for i,j in states:
        for action in actions:
            newpos = nextstate[i][j][action]
            newworld[i,j] += action_prob*(reward + world[newpos[0],newpos[1]]) 
            print(newworld)
    if n.sum(n.abs(world - newworld)) < 1e-4:
        print('Work over')
        print(newworld)
        break
    world = newworld    
        

[[ 0.   -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0.  -0.5  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]
[[ 0.   -0.75  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0. -1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.   -1.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0.  -1.  -0.5  0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]
[[ 0.   -1.   -0.75  0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.   -1.   -1.   -0.25]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0.  -1.  -1.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]
[[ 0.   -1.   -1.   -0

 [ 0.          0.          0.          0.        ]]
[[ 0.         -6.55693054 -8.97136688 -9.65983582]
 [-3.96884155  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -6.55693054 -8.97136688 -9.65983582]
 [-4.21884155  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -6.55693054 -8.97136688 -9.65983582]
 [-6.55693054  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -6.55693054 -8.97136688 -9.65983582]
 [-6.55693054 -1.78449249  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -6.55693054 -8.97136688 -9.65983582]
 [-6.55693054 -4.14144897  0.          0.        ]
 [ 0.          0.         

[[  0.         -10.34312295 -14.5811716  -15.93600926]
 [-10.34312295 -13.22633393 -14.61741342 -14.5811716 ]
 [-14.5811716  -14.61741342 -13.22633393 -10.34312295]
 [-15.93600926 -14.5811716  -10.34312295   0.        ]]
[[ 0.   -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
[[ 0.        -4.1452929  0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.       ]]
[[ 0.         -6.98107364  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[  0.         -10.53765712   0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -10.53765712  -2.83578074   0.        ]


[[  0.         -12.2988182  -17.47915494 -14.59464491]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -12.2988182  -17.47915494 -19.17902528]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -12.2988182  -17.47915494 -19.17902528]
 [ -3.30080937   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -12.2988182  -17.47915494 -19.17902528]
 [ -7.46443783   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -12.2988182  -17.47915494 -19.17902528]
 [ -7.71443783   0.           0.           0.        ]
 [  0.

 [-20.88616739 -14.01748347   0.           0.        ]]
[[  0.         -13.32830601 -19.00467047 -20.88616739]
 [-13.32830601 -17.12317354 -19.01132855 -19.00467047]
 [-19.00467047 -19.01132855 -17.12317354 -13.32830601]
 [-20.88616739 -19.00467047   0.           0.        ]]
[[  0.         -13.32830601 -19.00467047 -20.88616739]
 [-13.32830601 -17.12317354 -19.01132855 -19.00467047]
 [-19.00467047 -19.01132855 -17.12317354 -13.32830601]
 [-20.88616739 -19.00467047  -4.98718699   0.        ]]
[[  0.         -13.32830601 -19.00467047 -20.88616739]
 [-13.32830601 -17.12317354 -19.01132855 -19.00467047]
 [-19.00467047 -19.01132855 -17.12317354 -13.32830601]
 [-20.88616739 -19.00467047  -5.23718699   0.        ]]
[[  0.         -13.32830601 -19.00467047 -20.88616739]
 [-13.32830601 -17.12317354 -19.01132855 -19.00467047]
 [-19.00467047 -19.01132855 -17.12317354 -13.32830601]
 [-20.88616739 -19.00467047  -9.75566427   0.        ]]
[[  0.         -13.32830601 -19.00467047 -20.88616739]
 [-13

 [  0.           0.           0.           0.        ]]
[[  0.         -13.7488968  -19.62791028 -21.5836096 ]
 [-13.7488968  -17.67221096 -19.63039931 -19.62791028]
 [-19.62791028 -19.63039931 -17.67221096  -4.66344854]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.7488968  -19.62791028 -21.5836096 ]
 [-13.7488968  -17.67221096 -19.63039931 -19.62791028]
 [-19.62791028 -19.63039931 -17.67221096  -8.34714569]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.7488968  -19.62791028 -21.5836096 ]
 [-13.7488968  -17.67221096 -19.63039931 -19.62791028]
 [-19.62791028 -19.63039931 -17.67221096 -13.4988968 ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.7488968  -19.62791028 -21.5836096 ]
 [-13.7488968  -17.67221096 -19.63039931 -19.62791028]
 [-19.62791028 -19.63039931 -17.67221096 -13.7488968 ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.7488968  -19.62791028 -21.5836096 ]
 [-13

[[  0.         -13.90612866 -19.86089958 -21.8443384 ]
 [-13.90612866 -17.87746075 -19.86183007 -19.86089958]
 [-19.86089958   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.90612866 -19.86089958 -21.8443384 ]
 [-13.90612866 -17.87746075 -19.86183007 -19.86089958]
 [-19.86089958  -5.21327106   0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.90612866 -19.86089958 -21.8443384 ]
 [-13.90612866 -17.87746075 -19.86183007 -19.86089958]
 [-19.86089958  -9.93091503   0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.90612866 -19.86089958 -21.8443384 ]
 [-13.90612866 -17.87746075 -19.86183007 -19.86089958]
 [-19.86089958 -14.64855901   0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.90612866 -19.86089958 -21.8443384 ]
 [-13.90612866 -17.87746075 -19.86183007 -19.86089958]
 [-19.

 [  0.           0.           0.           0.        ]]
[[  0.         -13.96490754 -19.9479993  -21.94180814]
 [-13.96490754 -17.95419045 -19.94834715  -5.23636126]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.96490754 -19.9479993  -21.94180814]
 [-13.96490754 -17.95419045 -19.94834715 -10.47263067]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.96490754 -19.9479993  -21.94180814]
 [-13.96490754 -17.95419045 -19.94834715 -16.20726533]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.96490754 -19.9479993  -21.94180814]
 [-13.96490754 -17.95419045 -19.94834715 -19.9479993 ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.96490754 -19.9479993  -21.94180814]
 [-13

 [  0.           0.           0.           0.        ]]
[[  0.         -13.98688119 -19.98056028 -21.9782458 ]
 [ -8.49201417   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.98688119 -19.98056028 -21.9782458 ]
 [ -8.74201417   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.98688119 -19.98056028 -21.9782458 ]
 [-13.98688119   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.98688119 -19.98056028 -21.9782458 ]
 [-13.98688119  -3.74653603   0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.98688119 -19.98056028 -21.9782458 ]
 [-13

 [  0.           0.           0.           0.        ]]
[[  0.         -13.99509572 -19.99273274   0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99509572 -19.99273274  -5.24808111]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99509572 -19.99273274 -10.99593375]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99509572 -19.99273274 -16.7437864 ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99509572 -19.99273274 -21.9918675 ]
 [  0

 [-21.99678897 -19.9971306    0.           0.        ]]
[[  0.         -13.9980636  -19.9971306  -21.99678897]
 [-13.9980636  -17.99747223 -19.99714979 -19.9971306 ]
 [-19.9971306  -19.99714979 -17.99747223 -13.9980636 ]
 [-21.99678897 -19.9971306   -5.24924235   0.        ]]
[[  0.         -13.9980636  -19.9971306  -21.99678897]
 [-13.9980636  -17.99747223 -19.99714979 -19.9971306 ]
 [-19.9971306  -19.99714979 -17.99747223 -13.9980636 ]
 [-21.99678897 -19.9971306   -5.49924235   0.        ]]
[[  0.         -13.9980636  -19.9971306  -21.99678897]
 [-13.9980636  -17.99747223 -19.99714979 -19.9971306 ]
 [-19.9971306  -19.99714979 -17.99747223 -13.9980636 ]
 [-21.99678897 -19.9971306  -10.2485749    0.        ]]
[[  0.         -13.9980636  -19.9971306  -21.99678897]
 [-13.9980636  -17.99747223 -19.99714979 -19.9971306 ]
 [-19.9971306  -19.99714979 -17.99747223 -13.9980636 ]
 [-21.99678897 -19.9971306  -13.9980636    0.        ]]
[[ 0.   -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0. 

 [ -5.74968304   0.           0.           0.        ]]
[[  0.         -13.9992761  -19.99892731 -21.9987996 ]
 [-13.9992761  -17.99905503 -19.99893449 -19.99892731]
 [-19.99892731 -19.99893449 -17.99905503 -13.9992761 ]
 [-10.9993998    0.           0.           0.        ]]
[[  0.         -13.9992761  -19.99892731 -21.9987996 ]
 [-13.9992761  -17.99905503 -19.99893449 -19.99892731]
 [-19.99892731 -19.99893449 -17.99905503 -13.9992761 ]
 [-16.24911656   0.           0.           0.        ]]
[[  0.         -13.9992761  -19.99892731 -21.9987996 ]
 [-13.9992761  -17.99905503 -19.99893449 -19.99892731]
 [-19.99892731 -19.99893449 -17.99905503 -13.9992761 ]
 [-21.9987996    0.           0.           0.        ]]
[[  0.         -13.9992761  -19.99892731 -21.9987996 ]
 [-13.9992761  -17.99905503 -19.99893449 -19.99892731]
 [-19.99892731 -19.99893449 -17.99905503 -13.9992761 ]
 [-21.9987996   -5.74968304   0.           0.        ]]
[[  0.         -13.9992761  -19.99892731 -21.9987996 ]
 [-13

[[  0.         -13.99972938 -19.99959899 -21.99955125]
 [-13.99972938 -17.99964674 -19.99960167 -19.99959899]
 [-19.99959899 -19.99960167  -5.24989482   0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99972938 -19.99959899 -21.99955125]
 [-13.99972938 -17.99964674 -19.99960167 -19.99959899]
 [-19.99959899 -19.99960167  -8.99982337   0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99972938 -19.99959899 -21.99955125]
 [-13.99972938 -17.99964674 -19.99960167 -19.99959899]
 [-19.99959899 -19.99960167 -14.24971819   0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99972938 -19.99959899 -21.99955125]
 [-13.99972938 -17.99964674 -19.99960167 -19.99959899]
 [-19.99959899 -19.99960167 -17.99964674   0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99972938 -19.99959899 -21.99955125]
 [-13.99972938 -17.99964674 -19.99960167 -19.99959899]
 [-19.

[[  0.         -13.99990931 -19.99986561 -21.99984961]
 [-13.99990931 -17.99988161 -19.99986651 -19.99986561]
 [-10.49992927   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99990931 -19.99986561 -21.99984961]
 [-13.99990931 -17.99988161 -19.99986651 -19.99986561]
 [-14.24990532   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99990931 -19.99986561 -21.99984961]
 [-13.99990931 -17.99988161 -19.99986651 -19.99986561]
 [-19.99986561   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99990931 -19.99986561 -21.99984961]
 [-13.99990931 -17.99988161 -19.99986651 -19.99986561]
 [-19.99986561  -5.24996452   0.           0.        ]
 [  0.           0.           0.           0.        ]]
[[  0.         -13.99990931 -19.99986561 -21.99984961]
 [-13.99990931 -17.99988161 -19.99986651 -19.99986561]
 [-19.

In [40]:
for i,j in states:
    max_value = -500
    curr_action = 0
    index = 0
    for action in actions:
        newPosition = nextstate[i][j][action]
        value = reward + world[newPosition[0],newPosition[1]]
        if max_value < value:
            max_value = value
            curr_action = index
        index = index + 1
    policy[i,j] = curr_action
print('Best Policy')
print(policy)


Best Policy
[[ 0.  0.  0.  0.]
 [ 2.  0.  0.  3.]
 [ 2.  1.  1.  3.]
 [ 1.  1.  1.  0.]]
